name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: blu3-bird
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-dark.svg?palette=github-dark&color_snake=cyan&color_dots=#1e1e2e,#313244,#45475a,#585b70,#cdd6f4

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
